from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="Patient", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=255)), ("language", models.CharField(default="en", max_length=10)), ("abha_id", models.CharField(blank=True, max_length=100, null=True)), ("created_at", models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="Session", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(choices=[("in_progress", "In progress"), ("awaiting_summary", "Awaiting summary"), ("summary_ready", "Summary ready"), ("doctor_reviewed", "Doctor reviewed")], default="in_progress", max_length=30)), ("red_flag", models.BooleanField(default=False)), ("red_flag_reason", models.TextField(blank=True, null=True)), ("pushed_to_abdm", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="core.patient"))]),
        migrations.CreateModel(name="Transcript", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("turn", models.PositiveIntegerField()), ("speaker", models.CharField(choices=[("patient", "Patient"), ("ai", "AI")], max_length=10)), ("text", models.TextField()), ("input_mode", models.CharField(blank=True, choices=[("voice", "Voice"), ("touch", "Touch")], max_length=10, null=True)), ("timestamp", models.DateTimeField(auto_now_add=True)), ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transcripts", to="core.session"))], options={"ordering": ["turn", "id"]}),
        migrations.CreateModel(name="Document", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("image", models.ImageField(upload_to="documents/")), ("extracted_text", models.TextField(blank=True)), ("extracted_fields", models.JSONField(default=dict)), ("confidence", models.FloatField(default=0)), ("uploaded_at", models.DateTimeField(auto_now_add=True)), ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="core.session"))]),
        migrations.CreateModel(name="Summary", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("structured_json", models.JSONField(default=dict)), ("edited_by_doctor", models.BooleanField(default=False)), ("doctor_notes", models.TextField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("session", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="summary", to="core.session"))]),
        migrations.AddConstraint(model_name="transcript", constraint=models.UniqueConstraint(fields=("session", "turn"), name="unique_session_turn")),
    ]
