# Generated by Django 4.2.30 on 2026-08-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_method',
            field=models.CharField(choices=[('printed', 'Printed OCR'), ('handwritten', 'Handwritten OCR')], default='printed', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='abha_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='mode',
            field=models.CharField(choices=[('allopathic', 'Allopathic'), ('ayush', 'AYUSH (Ayurvedic)')], default='allopathic', max_length=20),
        ),
        migrations.AddField(
            model_name='transcript',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.JSONField(default=dict)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('abnormal_value', 'Abnormal Lab Value'), ('drug_interaction', 'Drug-Drug Interaction')], max_length=30)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_flags', to='core.document')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_flags', to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='ABDMPushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_bundle', models.JSONField(default=dict)),
                ('status', models.CharField(default='success', max_length=20)),
                ('response_payload', models.JSONField(default=dict)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abdm_push_logs', to='core.session')),
            ],
        ),
    ]
