# Generated by Django 4.2.30 on 2026-08-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_ocr_method_patient_abha_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='needed_clarification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('unclear_complaint', 'Unclear Complaint'), ('incomplete_document', 'Incomplete Document'), ('needs_reinterview', 'Needs Re-interview'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='token',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='session',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='token_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='token_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
