# Generated by Django 4.2.30 on 2026-08-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_token_receptionist_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='dimension_asked',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
