# Generated by Django 4.2.30 on 2026-08-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transcript_dimension_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='counter_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='red_flag_severity',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('moderate', 'Moderate')], max_length=20, null=True),
        ),
    ]
